name: Update Saham Widget

on:
  schedule:
    - cron: '*/30 * * * *'  # setiap 30 menit (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install yfinance pandas

      - name: Generate HTML
        run: python generate.py

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add saham_lq45.html
          git commit -m "Update saham_lq45.html"
          git push
