name: Update Saham Widget

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *'  # Jalankan tiap 30 menit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install yfinance

      - name: Generate HTML
        run: python generate.py

      - name: Commit generated HTML
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add ihsg-hari-ini.html
          git commit -m "Update ihsg-hari-ini.html" || echo "No changes"
          git push

      - name: Upload ihsg-hari-ini.html only
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.idxstock.com
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: /domains/idxstock.com/public_html/
          include: ihsg-hari-ini.html
